language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"

install:
  - pip install -r requirements.txt --use-mirrors
  - pip install coveralls pep8 flake8
script:
  - flake8 --exit-zero
  - ./runtests.py example
  - coverage run --source=. runtests.py
after_success:
  - coveralls
