language: python
dist: xenial
python:
  - "3.6"
  - "3.7"
  - "3.8"
env:
  - DJANGO=2.2.16
  - DJANGO=3.0.7
  - DJANGO=3.1.1
install:
  - pip install --upgrade pip
  - pip install .[files]
  - pip install .[huey]
  - pip install .[celery]
  - pip uninstall django-spirit -y
  - pip install -q Django==$DJANGO
  - pip install pep8==1.5.7 flake8
script:
  - flake8 --exit-zero
  - python setup.py build
  - python ./spirit/extra/bin/spirit.py startproject project
  - export PYTHONWARNINGS="default"
  - make test
notifications:
  email:
    on_failure: never
    on_success: never

jobs:
  include:
    - language: node_js
      node_js: 12
      script:
        - yarn
        - make testjs
      install: []
      env: []
      after_success: []
    - name: "No opt deps"
      language: python
      python: "3.8"
      install:
        - pip install --upgrade pip
        - pip install .
        - pip uninstall django-spirit -y
        - pip install -q Django==3.0.3
      script:
        - python ./spirit/extra/bin/spirit.py startproject project
        - export PYTHONWARNINGS="default"
        - export ST_UPLOAD_FILE_ENABLED=0
        - export ST_INSTALL_HUEY=0
        - python runtests.py
      env: []
      after_success: []
    - name: "Huey"
      language: python
      python: "3.8"
      install:
        - pip install --upgrade pip
        - pip install .
        - pip install .[huey]
        - pip uninstall django-spirit -y
        - pip install -q Django==3.0.3
      script:
        - python ./spirit/extra/bin/spirit.py startproject project
        - export PYTHONWARNINGS="default"
        - export ST_UPLOAD_FILE_ENABLED=0
        - export ST_TASK_MANAGER="huey"
        - python runtests.py
      env: []
      after_success: []
