name: CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Py ${{ matrix.python }} / Django ${{ matrix.django }}
    strategy:
      matrix:
        python: [3.6, 3.7, 3.8]
        django: [2.2.16, 3.0.7, 3.1.1]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[files]
        pip install .[huey]
        pip install .[celery]
        pip uninstall django-spirit -y
        pip install --upgrade Django==${{ matrix.django }}
    - name: Run Tests
      run: |
        python setup.py -q build
        python ./spirit/extra/bin/spirit.py startproject project
        cp ./project/manage.py ./manage.py
        python manage.py makemigrations --check --dry-run
        export PYTHONWARNINGS="default"
        make test
  build_js:
    runs-on: ubuntu-latest
    name: JS
    strategy:
      matrix:
        node: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Set Up NodeJS ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: Install Dependencies
      run: |
        npm install -g yarn
        npm install -g jasmine@3.6.1
        yarn
    - name: Run Tests
      run: |
        make testjs
  build_no_deps:
    runs-on: ubuntu-latest
    name: No-deps / Py ${{ matrix.python }} / Django ${{ matrix.django }}
    strategy:
      matrix:
        python: [3.8]
        django: [3.1.1]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip uninstall django-spirit -y
        pip install --upgrade Django==${{ matrix.django }}
    - name: Run Tests
      run: |
        python ./spirit/extra/bin/spirit.py startproject project
        export PYTHONWARNINGS="default"
        export ST_UPLOAD_FILE_ENABLED=0
        export ST_INSTALL_HUEY=0
        make test
